/**
 * 文件操作图标
 */

import {
  FileUp,
  FileDown,
  FolderPlus,
  FileEdit,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Cloud,
  UploadCloud,
  DownloadCloud,
  Save,
  ExternalLink,
  Maximize2,
  Minimize2,
  Trash2,
  ScrollText,
  BookText,
  Wrench,
  Inbox,
  RefreshCw,
  FolderUp,
} from 'lucide-react';

// 导出图标
export {
  FileUp,
  FileDown,
  FolderPlus,
  FileEdit,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Cloud,
  UploadCloud,
  DownloadCloud,
  Save,
  ExternalLink,
  Maximize2,
  Minimize2,
  Trash2,
  ScrollText,
  BookText,
  Wrench,
  Inbox,
  RefreshCw,
  FolderUp,
};

// 文件操作图标映射
export const fileIcons = {
  fileUp: FileUp,
  fileDown: FileDown,
  folderPlus: FolderPlus,
  fileEdit: FileEdit,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  rotateLeft: RotateCcw,
  cloud: Cloud,
  cloudUpload: UploadCloud,
  cloudDownload: DownloadCloud,
  save: Save,
  externalLink: ExternalLink,
  maximize: Maximize2,
  minimize: Minimize2,
  trashCan: Trash2,
  fileUpload: FileUp,
  folderUpload: FolderUp,
  journal: BookText,
  scrollText: ScrollText,
  wrench: Wrench,
  inbox: Inbox,
  arrowRepeat: RefreshCw,
};