/**
 * 图标模块入口
 * 统一导出所有 Lucide 图标
 */
import {
  // 导航和操作
  Server,
  Users,
  Home,
  Settings,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Plus,
  Minus,
  Search,
  Filter,
  RefreshCw,
  Download,
  Upload,
  Copy,
  Check,
  Pencil,
  Trash2,
  MoreHorizontal,
  MoreVertical,
  Eye,
  EyeOff,
  // 终端和连接
  Terminal,
  FolderOpen,
  Folder,
  File,
  FileText,
  Plug,
  PlugZap,
  Unplug,
  // 状态
  AlertCircle,
  AlertTriangle,
  Info,
  Ban,
  Clock,
  Loader2,
  CheckCircle2,
  XCircle,
  Circle,
  // 用户和认证
  User,
  Lock,
  Key,
  Shield,
  LogIn,
  ShieldCheck,
  // 系统和硬件
  HardDrive,
  Cpu,
  Monitor,
  Database,
  Tag,
  Globe,
  Hash,
  Zap,
  Power,
  Layers,
  Activity,
  TrendingUp,
  // 文件操作
  FileUp,
  FileDown,
  FolderPlus,
  FileEdit,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Cloud,
  UploadCloud,
  DownloadCloud,
  Save,
  ExternalLink,
  Maximize2,
  Minimize2,
  ScrollText,
  BookText,
  Wrench,
  Inbox,
  FolderUp,
  // 其他
  Box,
  CornerRightUp,
  ArrowDownCircle,
  AlertCircle as CircleExclamation,
  ArrowLeftRight,
  Loader2 as Spinner,
  LogOut as RightFromBracket,
  LogIn as RightToBracket,
  RotateCw,
  Search as MagnifyingGlass,
  PenSquare,
  ShieldHalf,
  Repeat,
  MoreVertical as EllipsisVertical,
  Trash2 as TrashCan,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

// 导出所有图标
export {
  // 导航和操作
  Server,
  Users,
  Home,
  Settings,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Plus,
  Minus,
  Search,
  Filter,
  RefreshCw,
  Download,
  Upload,
  Copy,
  Check,
  Pencil,
  Trash2,
  MoreHorizontal,
  MoreVertical,
  Eye,
  EyeOff,
  // 终端和连接
  Terminal,
  FolderOpen,
  Folder,
  File,
  FileText,
  Plug,
  PlugZap,
  Unplug,
  // 状态
  AlertCircle,
  AlertTriangle,
  Info,
  Ban,
  Clock,
  Loader2,
  CheckCircle2,
  XCircle,
  Circle,
  // 用户和认证
  User,
  Lock,
  Key,
  Shield,
  LogIn,
  ShieldCheck,
  // 系统和硬件
  HardDrive,
  Cpu,
  Monitor,
  Database,
  Tag,
  Globe,
  Hash,
  Zap,
  Power,
  Layers,
  Activity,
  TrendingUp,
  // 文件操作
  FileUp,
  FileDown,
  FolderPlus,
  FileEdit,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Cloud,
  UploadCloud,
  DownloadCloud,
  Save,
  ExternalLink,
  Maximize2,
  Minimize2,
  ScrollText,
  BookText,
  Wrench,
  Inbox,
  FolderUp,
  // 其他
  Box,
  CornerRightUp,
  ArrowDownCircle,
  ArrowLeftRight,
  RotateCw,
  PenSquare,
  ShieldHalf,
  Repeat,
};

// 导出类型
export type { LucideIcon, LucideProps };

// Font Awesome 到 Lucide 的图标映射
export const faToLucideMap: Record<string, LucideIcon> = {
  // 导航
  'fa-server': Server,
  'fa-users': Users,
  'fa-home': Home,
  'fa-cog': Settings,
  'fa-gear': Settings,
  'fa-sign-out': LogOut,
  'fa-right-from-bracket': LogOut,
  'fa-right-to-bracket': LogIn,
  'fa-bars': Menu,
  'fa-xmark': X,
  'fa-close': X,
  'fa-times': X,
  'fa-chevron-left': ChevronLeft,
  'fa-chevron-right': ChevronRight,
  'fa-chevron-up': ChevronUp,
  'fa-chevron-down': ChevronDown,
  'fa-plus': Plus,
  'fa-minus': Minus,
  'fa-search': Search,
  'fa-magnifying-glass': Search,
  'fa-filter': Filter,
  'fa-refresh': RefreshCw,
  'fa-rotate-right': RotateCw,
  'fa-rotate': RefreshCw,
  'fa-download': Download,
  'fa-circle-down': ArrowDownCircle,
  'fa-upload': Upload,
  'fa-copy': Copy,
  'fa-check': Check,
  'fa-check-circle': CheckCircle2,
  'fa-pencil': Pencil,
  'fa-edit': Pencil,
  'fa-pen': Pencil,
  'fa-trash': Trash2,
  'fa-trash-can': Trash2,
  'fa-ellipsis-h': MoreHorizontal,
  'fa-ellipsis-v': MoreVertical,
  'fa-ellipsis-vertical': MoreVertical,
  'fa-eye': Eye,
  'fa-eye-slash': EyeOff,
  
  // 终端和连接
  'fa-terminal': Terminal,
  'fa-folder': Folder,
  'fa-folder-open': FolderOpen,
  'fa-folder-plus': FolderPlus,
  'fa-file': File,
  'fa-file-lines': FileText,
  'fa-file-text': FileText,
  'fa-plug': Plug,
  'fa-plug-circle-check': Plug,
  'fa-plug-circle-xmark': Unplug,
  
  // 状态
  'fa-circle-exclamation': AlertCircle,
  'fa-exclamation-circle': AlertCircle,
  'fa-exclamation-triangle': AlertTriangle,
  'fa-triangle-exclamation': AlertTriangle,
  'fa-info': Info,
  'fa-info-circle': Info,
  'fa-circle-info': Info,
  'fa-ban': Ban,
  'fa-clock': Clock,
  'fa-spinner': Loader2,
  'fa-circle-notch': Loader2,
  'fa-circle-check': CheckCircle2,
  'fa-circle-xmark': XCircle,
  'fa-circle': Circle,
  
  // 用户和认证
  'fa-user': User,
  'fa-lock': Lock,
  'fa-key': Key,
  'fa-shield': Shield,
  'fa-shield-halved': ShieldHalf,
  'fa-shield-check': ShieldCheck,
  'fa-login': LogIn,
  
  // 系统和硬件
  'fa-hard-drive': HardDrive,
  'fa-hdd': HardDrive,
  'fa-microchip': Cpu,
  'fa-cpu': Cpu,
  'fa-desktop': Monitor,
  'fa-monitor': Monitor,
  'fa-database': Database,
  'fa-tag': Tag,
  'fa-globe': Globe,
  'fa-hashtag': Hash,
  'fa-bolt': Zap,
  'fa-zap': Zap,
  'fa-power-off': Power,
  'fa-power': Power,
  'fa-layer-group': Layers,
  'fa-chart-line': TrendingUp,
  'fa-activity': Activity,
  'fa-trending-up': TrendingUp,
  
  // 文件操作
  'fa-file-up': FileUp,
  'fa-file-down': FileDown,
  'fa-file-upload': FileUp,
  'fa-file-download': FileDown,
  'fa-file-edit': FileEdit,
  'fa-file-pen': FileEdit,
  'fa-pen-to-square': PenSquare,
  'fa-arrow-up': ArrowUp,
  'fa-arrow-down': ArrowDown,
  'fa-arrow-right': ArrowRight,
  'fa-arrow-left': ArrowLeft,
  'fa-arrow-turn-up': CornerRightUp,
  'fa-rotate-ccw': RotateCcw,
  'fa-cloud': Cloud,
  'fa-cloud-arrow-up': UploadCloud,
  'fa-cloud-arrow-down': DownloadCloud,
  'fa-cloud-upload': UploadCloud,
  'fa-cloud-download': DownloadCloud,
  'fa-save': Save,
  'fa-floppy-disk': Save,
  'fa-external-link': ExternalLink,
  'fa-expand': Maximize2,
  'fa-maximize': Maximize2,
  'fa-minimize': Minimize2,
  'fa-scroll': ScrollText,
  'fa-book': BookText,
  'fa-wrench': Wrench,
  'fa-inbox': Inbox,
  'fa-folder-upload': FolderUp,
  'fa-right-left': ArrowLeftRight,
  'fa-arrow-repeat': Repeat,
  
  // 其他
  'fa-cube': Box,
};

// Bootstrap Icons 到 Lucide 的映射
export const biToLucideMap: Record<string, LucideIcon> = {
  'bi-x-lg': X,
  'bi-x': X,
  'bi-plus-lg': Plus,
  'bi-plus': Plus,
  'bi-people': Users,
  'bi-person': User,
  'bi-journal-text': BookText,
  'bi-journal': ScrollText,
  'bi-shield-check': ShieldCheck,
  'bi-shield': Shield,
  'bi-wrench': Wrench,
  'bi-eye': Eye,
  'bi-pencil': Pencil,
  'bi-key': Key,
  'bi-trash': Trash2,
  'bi-arrow-repeat': Repeat,
  'bi-inbox': Inbox,
};

// 默认导出
export default {
  faToLucideMap,
  biToLucideMap,
};